/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 79 1",
"  c #7F7E7B",
". c #8D8B88",
"X c #908F8C",
"o c #A1A09C",
"O c #A2A19D",
"+ c #A5A4A0",
"@ c #A7A6A2",
"# c #ABA9A5",
"$ c #ACAAA6",
"% c #AEACA8",
"& c #AFADA9",
"* c #B6B4B0",
"= c #B7B5B1",
"- c #BAB8B3",
"; c #BAB8B4",
": c #BBB9B4",
"> c #BBB9B5",
", c #BBBAB5",
"< c #BCBAB6",
"1 c #BEBCB8",
"2 c #C0BEB9",
"3 c #C1BFBB",
"4 c #C2C0BC",
"5 c #C3C1BC",
"6 c #C4C2BD",
"7 c #C7C5C1",
"8 c #C8C6C1",
"9 c #C8C6C2",
"0 c #C8C7C2",
"q c #C9C7C2",
"w c #C9C7C3",
"e c #C9C8C3",
"r c #CAC8C3",
"t c #CAC8C4",
"y c #CBC9C4",
"u c #CBC9C5",
"i c #CBCAC5",
"p c #CCCAC5",
"a c #CCCAC6",
"s c #CDCBC6",
"d c #CECCC7",
"f c #CECCC8",
"g c #CECDC8",
"h c #CFCDC8",
"j c #CFCDC9",
"k c #CFCEC9",
"l c #D0CEC9",
"z c #D0CECA",
"x c #D0CFCA",
"c c #D1CFCA",
"v c #D1D0CB",
"b c #D2D0CB",
"n c #D2D1CC",
"m c #D3D1CC",
"M c #D4D2CD",
"N c #D5D3CE",
"B c #D5D4CF",
"V c #D6D4CF",
"C c #D7D5CF",
"Z c #D6D5D0",
"A c #D7D5D0",
"S c #D7D6D0",
"D c #D7D6D1",
"F c #D8D5D0",
"G c #D8D6D0",
"H c #D8D6D1",
"J c #D9D6D1",
"K c #D9D7D2",
"L c #DAD8D2",
"P c #DAD8D3",
"I c #DBD9D4",
"U c #DCDAD5",
"Y c #DDDBD5",
"T c #DDDBD6",
"R c #DEDCD6",
"E c #DEDCD7",
"W c #DFDDD8",
"Q c #E0DED9",
"! c #E4E2DC",
/* pixels */
"MMMMNNNMHPKKKKPN",
"kpCMNNMN!EEEEWCc",
"kuCMNNMCWcHMNNwk",
"kuCMNNMCWN3c6cpk",
"dqMMMmMCIIo& 7kf",
"llRIIIIIQH*3<lpk",
"kKRPIPIHPMKHHHwl",
"lVMVHHCkMllllcpl",
"kCP3<&kcPPHHCIcl",
"lMW#@.=CCMHHHMwl",
"lCH6,,llCH1;&Hpl",
"kCCHPKHlNEO+.wpk",
"cpww9999PH31<Mpl",
"kwMclmcVQlHHHM9l",
"kMQWWWIQIlmllMfc",
"MHPKPPIPHPKKKKKM"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 138 2",
"   c #464543",
".  c #595956",
"X  c #5C5B59",
"o  c #5D5C5A",
"O  c #5E5E5B",
"+  c #605F5D",
"@  c #656461",
"#  c #666562",
"$  c #6E6C6A",
"%  c #6F6E6B",
"&  c #716F6D",
"*  c #72716E",
"=  c #757471",
"-  c #797875",
";  c #807F7C",
":  c #82807D",
">  c #84837F",
",  c #848380",
"<  c #878682",
"1  c #888783",
"2  c #898884",
"3  c #898885",
"4  c #8A8885",
"5  c #8C8B87",
"6  c #8E8C89",
"7  c #91908C",
"8  c #93928F",
"9  c #999794",
"0  c #999894",
"q  c #9A9895",
"w  c #9F9D99",
"e  c #A09F9B",
"r  c #A2A09C",
"t  c #A3A29E",
"y  c #A5A39F",
"u  c #B1AFAB",
"i  c #B1B0AC",
"p  c #B5B3AF",
"a  c #B6B5B1",
"s  c #B9B7B3",
"d  c #BAB8B3",
"f  c #BAB8B4",
"g  c #BBB9B5",
"h  c #BCBBB6",
"j  c #BDBBB7",
"k  c #BDBCB8",
"l  c #BEBCB8",
"z  c #BEBDB8",
"x  c #BFBDB9",
"c  c #BFBEB9",
"v  c #C0BEB9",
"b  c #C0BEBA",
"n  c #C0BFBA",
"m  c #C1BFBB",
"M  c #C1C0BB",
"N  c #C2C0BC",
"B  c #C3C1BD",
"V  c #C4C2BD",
"C  c #C4C2BE",
"Z  c #C5C3BE",
"A  c #C5C3BF",
"S  c #C6C4C0",
"D  c #C6C5C0",
"F  c #C7C5C1",
"G  c #C7C6C1",
"H  c #C8C6C1",
"J  c #C9C7C2",
"K  c #CAC8C3",
"L  c #CAC8C4",
"P  c #CBC9C4",
"I  c #CBCAC5",
"U  c #CCCAC5",
"Y  c #CCCAC6",
"T  c #CDCBC6",
"R  c #CECCC7",
"E  c #CECCC8",
"W  c #CFCDC8",
"Q  c #CFCDC9",
"!  c #CFCEC9",
"~  c #D0CEC9",
"^  c #D1CFCA",
"/  c #D1CFCB",
"(  c #D1D0CB",
")  c #D2D0CB",
"_  c #D2D0CC",
"`  c #D2D1CC",
"'  c #D3D1CC",
"]  c #D4D2CD",
"[  c #D4D3CE",
"{  c #D5D3CE",
"}  c #D6D3CE",
"|  c #D6D4CE",
" . c #D6D4CF",
".. c #D6D5CF",
"X. c #D7D5CF",
"o. c #D6D5D0",
"O. c #D7D5D0",
"+. c #D7D6D0",
"@. c #D7D6D1",
"#. c #D8D5D0",
"$. c #D8D6D0",
"%. c #D8D6D1",
"&. c #D9D7D1",
"*. c #D9D7D2",
"=. c #DAD8D2",
"-. c #DAD8D3",
";. c #DBD8D3",
":. c #DBD9D3",
">. c #DBD9D4",
",. c #DCDAD5",
"<. c #DCDBD5",
"1. c #DDDBD5",
"2. c #DCDBD6",
"3. c #DDDBD6",
"4. c #DEDCD7",
"5. c #DFDDD7",
"6. c #DFDDD8",
"7. c #E0DED9",
"8. c #E1DFD9",
"9. c #E1DFDA",
"0. c #E2E0DA",
"q. c #E2E0DB",
"w. c #E3E1DB",
"e. c #E3E1DC",
"r. c #E4E2DC",
"t. c #E6E4DE",
"y. c #E6E4DF",
"u. c #E7E6E0",
"i. c #E9E7E1",
"p. c #E9E7E2",
"a. c #EAE8E2",
"s. c #EBE9E3",
"d. c #EBE9E4",
"f. c #ECEAE4",
"g. c #ECEAE5",
"h. c #EDEBE6",
"j. c #EEECE6",
"k. c #EEECE7",
/* pixels */
"] ] ] ] } } } } [ } [ } [ } [ [ / [ / ] ] ] / ] / ] ] / ] ] ] } ",
"} ] ] ] ] } [ } } [ } [ } [ [ [ } :.O.:.;.;.;.:.>.O.O.:.;.;.} ] ",
"..Q v O.[ [ } [ [ } [ } [ } [ [ j.f.p.p.s.p.s.p.s.s.s.s.f.:./ } ",
"..Q l ..[ } [ } } [ } [ } [ } [ f.] / ] ! ] ^ ] / / / / } g R } ",
"..! v O.[ ] ] ] [ } [ } [ } } ] f...] O.] ] ] ] ] [ } } ..v Q ..",
"O.! l O.[ ] } } } [ } [ } } } ] f.O.] ] ] [ ] ] [ [ } ] ..l Q ..",
"O.E l ..[ [ } } [ } [ } [ } } ] d.O.] ] ] 9.#./ ..6.] ] ..v Q } ",
"] Q l ..[ } [ } } [ } [ } [ } ] d...] O.! ; S 9.v < O.] O.l Q ..",
"..E v #.] } ] ] O.O.] ] ] } } ] f.O.] ] *.X g ! 9 O *.] O.l ! O.",
"O.! l #.] } O.] ] ] ] O.} ] } ] f.O.] ^ y.$ m e 1   S O...v ! ] ",
"] ! l ] ^ ^ ^ ! ^ ! ] ! ! ^ ! ! f.O.] ] / . t 9.F & ..] O.v ! ] ",
"O.E B y.9.9.y.y.y.9.y.y.y.9.y.y.k.] ] ] ^ R ! ] ] ..] ] O.v ! #.",
"O.U ! k.9.y.y.9.9.y.y.9.y.9.y.O.9.*.] ] ] ....] ] ] ] ] O.v E O.",
"O.U ! 9.! ! ! ] ^ ! ^ ] ^ ! ] v >.>.] O.] [ ] ....] ..] #.l E O.",
"O.U ! 9.^ } ] } } } ] ] ] ] O.H >.] ! ! Q Q Q Q ! ! Q Q / f E ] ",
"O.U / 9.^ } ] ] ] ] O.O.] ] O.H ] E U U Y Y Y Y U U U U U H ] ] ",
"O.U / 9.] ] ] O.] O.H ! >.] O.B 9.y.y.9.w.w.r.r.r.r.w.w.t.! ! } ",
"O.U / 9.^ / 9.= r p & < p *.O.S >.O.! / / / / / ~ / / / } d ! } ",
"O.U / 9./ ] 9.1 5 w.B @ u >.O.S >.:.] } } [ } } } } [ [ O.c ! } ",
"O.U / 9.^ ^ y.1 5 U l - 9 9.] B 4.;.] } [ [ } } } :.} ` ..c ! } ",
"O.U / 9.! ] >.5 7 j < 7 Y ] ..S 4.:./ } } $.] } R A ] ] O.l ! } ",
"O.U / 9.] } ] >.;.O.>.>.O.] O.F >.:.} } ! O R 0 @ u / } O.v ! ..",
"} U / 9.! ] ] / [ ] ] [ ] ] ..B >.:./ / 9.@ v g - q ] ] O.l ! } ",
"O.U ! y.] O.O.O.] O.O...O...*.F 4.:./ / 7.@ d d ..@ g *...v ! } ",
"O.U ] O.H U L L P J U Y Y J U l <.:./ } ~ * u y : w O.] O.v ! ] ",
"} ! B H v m B m v V B v B v B v t.+.} } [ 4.+.1.>.>.] ] O.v ! O.",
"} ! j O.O.O.O.O.} $.:.$.O.O.:...f.} } [ [ / [ ` ] [ ] ] } l ! ] ",
"O.! v O.] ] ] ] [ [ [ } } ] ] [ f.:.$.} $.} +.+...O.] O.>.v ! #.",
"} ! g ] ] ] / ] / / / $./ / / / u.Y F A Z J Z J A J J J J a ! } ",
"} W ! j.y.f.s.y.p.p.y.y.s.s.s.f.s...+.+.+.+.=.$.:.+.} } O.O.} ] ",
"} ] O.>.O.:.>.;.:.:.:.:.=.=.=.=.=.4.4.4.1.4.4.4.4.<.4.4.4.>.} ] ",
"] } ] ] ] / ] ] [ / / [ / [ ` / [ / / / / / / / / / / / / [ ] } "
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 227 2",
"   c #1D1D1C",
".  c #2D2C2B",
"X  c #333231",
"o  c #383836",
"O  c #393837",
"+  c #3A3A38",
"@  c #3F3E3D",
"#  c #40403E",
"$  c #424140",
"%  c #444342",
"&  c #464543",
"*  c #464544",
"=  c #474644",
"-  c #4A4947",
";  c #4B4A48",
":  c #4E4D4C",
">  c #4F4E4C",
",  c #51514F",
"<  c #545351",
"1  c #555452",
"2  c #565553",
"3  c #5B5A58",
"4  c #5D5C5A",
"5  c #5D5D5A",
"6  c #5F5E5C",
"7  c #605F5D",
"8  c #61605E",
"9  c #6A6966",
"0  c #6C6B69",
"q  c #6D6C69",
"w  c #6E6D6A",
"e  c #706F6C",
"r  c #71706D",
"t  c #71706E",
"y  c #72706E",
"u  c #72716E",
"i  c #73726F",
"p  c #747370",
"a  c #777673",
"s  c #797875",
"d  c #7C7B78",
"f  c #7F7D7A",
"g  c #7F7E7B",
"h  c #807F7C",
"j  c #817F7C",
"k  c #81807D",
"l  c #82817E",
"z  c #83817E",
"x  c #858481",
"c  c #868582",
"v  c #878682",
"b  c #888783",
"n  c #898885",
"m  c #8A8985",
"M  c #8E8C89",
"N  c #92918D",
"B  c #93928E",
"V  c #959390",
"C  c #969491",
"Z  c #969591",
"A  c #989793",
"S  c #9A9895",
"D  c #9E9C98",
"F  c #A09F9B",
"G  c #A3A19E",
"H  c #A4A39F",
"J  c #A6A4A0",
"K  c #A7A5A1",
"L  c #A8A7A3",
"P  c #A9A8A4",
"I  c #ACABA7",
"U  c #ADACA8",
"Y  c #AFADA9",
"T  c #AFAEAA",
"R  c #B0AFAA",
"E  c #B0AFAB",
"W  c #B1AFAB",
"Q  c #B1B0AC",
"!  c #B2B1AC",
"~  c #B2B1AD",
"^  c #B3B1AD",
"/  c #B3B2AE",
"(  c #B4B2AE",
")  c #B4B3AE",
"_  c #B4B3AF",
"`  c #B5B3AF",
"'  c #B5B4B0",
"]  c #B6B4B0",
"[  c #B6B5B0",
"{  c #B6B5B1",
"}  c #B7B5B1",
"|  c #B7B6B1",
" . c #B7B6B2",
".. c #B8B6B2",
"X. c #B8B7B3",
"o. c #B9B7B2",
"O. c #B9B7B3",
"+. c #B9B8B3",
"@. c #B9B8B4",
"#. c #BAB9B4",
"$. c #BAB9B5",
"%. c #BBB9B5",
"&. c #BBBAB5",
"*. c #BBBAB6",
"=. c #BCBAB6",
"-. c #BCBBB6",
";. c #BDBBB7",
":. c #BDBCB8",
">. c #BFBDB9",
",. c #C0BEBA",
"<. c #C0BFBA",
"1. c #C1BFBB",
"2. c #C1C0BB",
"3. c #C3C1BD",
"4. c #C3C2BD",
"5. c #C4C2BD",
"6. c #C4C2BE",
"7. c #C4C3BE",
"8. c #C6C5C0",
"9. c #C7C5C1",
"0. c #C8C6C1",
"q. c #C9C7C2",
"w. c #CAC8C3",
"e. c #CAC8C4",
"r. c #CBC9C4",
"t. c #CCCAC5",
"y. c #CDCBC6",
"u. c #CDCBC7",
"i. c #CDCCC7",
"p. c #CECCC7",
"a. c #CFCDC8",
"s. c #CFCDC9",
"d. c #CFCEC9",
"f. c #D0CEC9",
"g. c #D0CECA",
"h. c #D1CFCA",
"j. c #D1D0CB",
"k. c #D2D0CB",
"l. c #D1D1CD",
"z. c #D2D1CC",
"x. c #D2D1CD",
"c. c #D3D1CC",
"v. c #D2D2CD",
"b. c #D3D2CD",
"n. c #D4D2CD",
"m. c #D5D2CD",
"M. c #D5D3CE",
"N. c #D6D4CF",
"B. c #D7D4CF",
"V. c #D7D5D0",
"C. c #D8D5D0",
"Z. c #D8D6D0",
"A. c #D8D6D1",
"S. c #D9D6D1",
"D. c #D9D7D1",
"F. c #D9D7D2",
"G. c #DAD8D2",
"H. c #DAD8D3",
"J. c #DBD9D3",
"K. c #DBD9D4",
"L. c #DBD9D5",
"P. c #DCDAD4",
"I. c #DCDAD5",
"U. c #DDDAD5",
"Y. c #DDDBD5",
"T. c #DCDBD6",
"R. c #DDDBD6",
"E. c #DEDCD7",
"W. c #DEDDD7",
"Q. c #DFDDD7",
"!. c #DFDDD8",
"~. c #DFDED8",
"^. c #E0DDD8",
"/. c #E0DED9",
"(. c #E1DED9",
"). c #E1DFD9",
"_. c #E1DFDA",
"`. c #E2E0DA",
"'. c #E2E0DB",
"]. c #E3E0DB",
"[. c #E3E1DB",
"{. c #E3E1DC",
"}. c #E4E2DD",
"|. c #E5E2DD",
" X c #E5E3DD",
".X c #E5E3DE",
"XX c #E6E3DE",
"oX c #E6E4DE",
"OX c #E6E4DF",
"+X c #E7E5DF",
"@X c #E7E5E0",
"#X c #E7E6E0",
"$X c #E8E6E0",
"%X c #E8E7E1",
"&X c #E8E7E2",
"*X c #E8E7E3",
"=X c #E9E7E2",
"-X c #EAE8E2",
";X c #EAE8E3",
":X c #EAE9E3",
">X c #EBE8E3",
",X c #EBE9E3",
"<X c #EBE9E4",
"1X c #ECEAE4",
"2X c #ECEAE5",
"3X c #EDEBE5",
"4X c #ECEBE6",
"5X c #EDEBE6",
"6X c #EEECE6",
"7X c #EEECE7",
"8X c #EFECE7",
"9X c #F0EDE8",
"0X c #F0EEE9",
"qX c #F1EFE9",
"wX c #F2EFEA",
"eX c #F2F1EB",
"rX c #F3F1EB",
"tX c #F3F1EC",
"yX c #F4F2EC",
"uX c #F4F2ED",
"iX c #F5F3ED",
"pX c #F5F3EE",
"aX c #F5F4EF",
"sX c #F6F4EF",
"dX c #F9F7F1",
"fX c #F9F7F2",
"gX c #FFFFFA",
/* pixels */
"M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.C.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.",
"M.M.M.M.M.M.k.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.h.M.M.M.M.M.M.M.M.M.N.M.M.M.M.M.N.M.M.M.M.M.M.M.M.",
"M.M.k.N.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.h.h.h.g.g.g.g.g.h.h.h.h.g.h.h.h.g.g.g.k.N.M.M.M.",
"M.M.N.d.t.N.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.^.XXXXXX XXXXXXX X X X X X X X X XXX+X[.h.M.M.M.",
"M.M.A.6.#.A.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.h.iXqX1X3X3X3X3X3X3X3X3X3X3X3X1X1X3X1X3Xp.h.N.N.M.",
"M.M.A.6.-.A.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.rXN.a.g.h.h.h.h.h.g.h.h.h.h.g.g.g.g.p.W h.N.h.M.",
"M.M.A.6.-.A.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.yXJ.M.M.M.M.N.M.M.M.M.M.N.M.M.M.N.B.k.) M.N.M.M.",
"M.h.A.6.-.A.k.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.h.yXJ.k.M.M.M.M.M.M.M.M.M.M.M.M.M.k.N.k.) h.N.M.M.",
"M.M.A.6.=.S.h.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.k.yXJ.k.N.M.M.M.M.M.M.M.M.M.M.M.M.k.M.k.) k.M.k.M.",
"M.M.A.6.-.S.m.C.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.yXA.k.M.M.M.M.h.k.V.M.M.k.k.M.M.M.V.k.) k.M.V.M.",
"M.h.A.6.-.A.M.m.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.k.yXH.k.M.M.M.N.[.H.k.M.k.H._.M.M.M.M.k.' k.V.M.M.",
"M.M.A.6.-.A.M.m.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.k.yXH.M.M.M.M.h.x G !.g.!.| h J.k.k.M.k.' k.M.k.M.",
"M.M.A.6.-.A.M.m.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.yXA.k.M.k.M.M.% p  XA.4.9 + T.M.M.M.l.) k.V.k.M.",
"M.M.A.6.-.A.h.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.k.yXJ.M.M.M.g.,Xa q 4X| A | # ~.k.M.M.k.) k.M.V.M.",
"M.h.A.6.-.A.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.k.yXH.k.N.N.h.=Xe e iXk a e   P H.k.M.k.) k.V.k.M.",
"M.M.A.6.-.A.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.yXH.k.M.M.k.!.4 5 T.V.V.I o H.k.M.V.k.) k.M.M.M.",
"V.k.V.7.#.N.h.h.h.h.h.h.h.h.h.h.g.h.h.h.h.h.h.g.rXJ.M.M.M.A.6.k k 4.V.V.8.Z V.V.M.M.k.| k.V.k.M.",
"N.N.V.4.4.,X@X X+X X=X X X=X X@X=X X X=X+X X=X XsXA.k.M.M.k.V.{.{.V.k.V.V.~.k.M.k.M.k./ k.M.V.M.",
"M.k.J.>.k.fX@X,X1X1X,X,X1X1X,X,X,X1X1X,X1X,X3XM.,XR.k.M.M.M.M.g.d.M.k.V.M.k.M.M.V.k.k.' k.V.k.M.",
"N.M.H.>.k.@Xt.h.h.h.h.h.h.h.h.g.g.h.h.g.g.g.M.~ @XR.k.M.M.M.M.M.V.k.V.V.M.M.M.M.k.V.k./ k.M.M.M.",
"M.M.J.>.k.,Xh.N.N.M.M.M.M.M.M.M.N.M.M.M.M.M.A.X.@XH.k.k.M.M.M.k.k.V.k.k.N.k.k.N.V.k.k.~ k.V.V.M.",
"M.k.H.>.h.,Xd.N.M.M.M.M.M.M.M.M.M.M.M.M.N.k.A.| ,X{.A.H.A.A.J.A.H.H.H.F.A.H.H.H.H.H.V.' k.M.k.M.",
"V.V.V.>.N.,Xg.N.M.M.M.M.M.M.M.M.M.N.N.M.M.M.A.o.{.4.#.*.#.#.#.#.#.#.#.#.#.#.#.#.#.:.#.I M.M.k.M.",
"k.k.V.4.h.,Xa.N.h.M.N.h.h.M.M.g.h.h.M.M.M.k.A.o.!.!.H.T.!.R.R.R.T.T.!.T.T.!.T.T.T.H.!.V.k.V.M.M.",
"V.k.H.>.k.*Xd.N.M.M.k._._.k.V.@X!.!.k.V.V.k.V.| #X,X{.{.{.{.{.@XXX{.{. X{. X{. XXXXXXX>.h.M.M.M.",
"V.k.H.>.V.,Xh.k.M.k.A.S f R.q.8 p l H.k.k.V.V.X.@XF.d.k.k.k.h.d.g.g.h.h.g.k.h.g.g.h.u.T M.M.M.M.",
"V.k.H.>.k.,Xd.N.M.M.H.f o ,XK 2  X6 s {.k.k.V.X.@X!.k.k.M.M.N.M.M.M.M.M.V.M.M.M.M.M.M.} h.M.M.M.",
"k.V.H.>.k.,Xd.N.M.k.!.| @ R.A._.m * 4.H.k.V.V. .#XT.k.V.M.M.M.M.M.M.M.M.k.V.M.M.k.M.h.} h.M.h.M.",
"N.N.H.>.k.,Xd.M.N.k.R.T %  Xh.k.H.9 d XXk.k.V. .,XH.k.V.M.k.V.k.V.M.k.V.M.k.k.V.M.M.k./ M.M.M.M.",
"k.k.H.>.M.,Xd.M.M.k.R.Z . V.H > d.1 x [.k.N.H. .@XR.k.k.k.V.M.k.k.V.M.k.V.V.V.k.M.M.k./ h.M.M.M.",
"V.k.J.>.k.,Xd.N.k.N.k.Z k W A.B x D _.k.V.k.V.| @XR.k.V.V.k.V.!.V.k.V.k.8.t.k.V.k.V.k.| h.C.M.M.",
"N.N.H.>.k.,Xd.M.M.M.N._.XXH.k._.XX!.h.N.k.N.V.| ,XH.k.V.k.V.u.< c ,X~ * B f 7.H.k.V.k.~ h.M.M.M.",
"k.N.J.>.M.,Xd.M.M.M.M.g.g.M.M.g.h.h.C.h.M.M.H. .=XR.h.m.k.k._.3 e wXH X T g.P.k.M.M.k.) N.N.M.M.",
"V.k.H.>.k.,Xg.M.M.M.M.M.M.M.M.M.M.M.M.M.C.h.V. .=XH.h.C.M.g.=Xe 0 +Xh.H b : r.B.M.M.k.) h.N.k.M.",
"M.V.V.>.x.*Xd.M.k.M.M.M.k.M.M.M.h.C.h.M.M.h.V. .=XR.M.M.M.g.1Xp i 9Xo.S.gX; F _.k.M.k.^ h.N.M.N.",
"M.k.V.4.k.4XM.V.A.A.A.A.S.A.A.A.S.H.H.C.C.V.^. .=XR.h.M.M.M.M.; = [.i 7 M 1 g.M.M.M.M.^ k.N.k.M.",
"M.k.V.1.k.V. .>.;.-.;.;.;.;.;.;.:.=.:.>.:.:.:.I =XA.k.M.M.B.q.T T r.A.T H k.A.M.M.N.k.) M.N.M.M.",
"V.M.V.4.>.t.1.4.1.6.6.1.6.1.6.6.8.1.1.1.1.8.1.8.rXA.M.M.M.M.B.R.Y.A.M.R._.B.k.M.k.N.k.) h.N.k.M.",
"k.M.V.8.#.L.A.A.S.S.A.A.A.A.A.A.A.A.V.V.C.A.V.V.yXR.M.M.M.M.M.g.M.M.M.k.k.k.m.M.M.N.M.) h.N.M.N.",
"V.k.V.8.*.V.k.M.M.M.M.k.M.M.k.M.M.M.M.M.h.M.M.h.yXV.g.M.M.h.M.M.M.k.k.M.M.M.M.M.k.M.k.) k.N.k.M.",
"M.M.A.6.:.V.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.pXV.h.M.M.M.h.M.M.M.M.M.M.M.M.M.M.N.k.) k.N.k.V.",
"M.M.A.8.:.V.h.M.M.M.M.M.M.h.M.M.M.M.M.M.M.h.M.h.pXL.M.M.M.C.M.M.M.M.M.C.M.M.M.V.N.N.M./ k.V.k.M.",
"M.h.A.1.#.R.M.M.M.M.m.C.M.M.M.M.M.M.M.M.M.M.M.A.1X .}  . . .o.o.| |  . .| |  . .| | | ~ k.V.M.N.",
"M.M.A.q.V.fXyXpXyXyXyXyXpXyXpXyXpXpXpXpXpXyXpXpXyX4X8X4X4X4X4X4X4X4X4X4X4X4X1X1X3X3X7X,XV.k.M.M.",
"M.M.M.M.V.M.A.M.M.M.M.M.M.M.M.C.M.M.M.M.M.M.M.M.M.A.C.C.C.C.C.A.C.C.C.C.A.A.A.A.A.V.J.V.k.k.V.M.",
"M.M.M.M.h.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.h.M.M.M.M.M.M.M.h.M.M.M.h.M.k.M.k.M.k.k.k.V.M.M.M.",
"M.M.M.h.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.N.M.M.M.M.M.M.M.",
"M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M."
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
};
const int n_xpm_icons = 3;
