/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 71 1",
"  c #73726F",
". c #7B7A77",
"X c #8C8B88",
"o c #9C9A97",
"O c #A3A29E",
"+ c #AAA8A4",
"@ c #AAA9A5",
"# c #ADACA8",
"$ c #B0AEAA",
"% c #B1AFAB",
"& c #B1B0AC",
"* c #BBB9B5",
"= c #BCBBB6",
"- c #BDBBB7",
"; c #BEBDB8",
": c #C4C2BE",
"> c #C7C5C0",
", c #C8C7C2",
"< c #C9C7C2",
"1 c #C9C7C3",
"2 c #CAC8C3",
"3 c #CAC8C4",
"4 c #CBC9C4",
"5 c #CBC9C5",
"6 c #CBCAC5",
"7 c #CCCAC5",
"8 c #CCCAC6",
"9 c #CDCBC6",
"0 c #CDCCC7",
"q c #CECCC7",
"w c #CECCC8",
"e c #CECDC8",
"r c #CFCDC8",
"t c #CFCDC9",
"y c #CFCEC9",
"u c #D0CEC9",
"i c #D0CECA",
"p c #D1CFCA",
"a c #D1CFCB",
"s c #D1D0CB",
"d c #D2D0CB",
"f c #D3D1CC",
"g c #D4D2CD",
"h c #D4D3CE",
"j c #D5D3CE",
"k c #D5D4CF",
"l c #D6D4CF",
"z c #D7D5D0",
"x c #D8D6D0",
"c c #D8D6D1",
"v c #D9D7D1",
"b c #D9D7D2",
"n c #DAD7D2",
"m c #D9D8D2",
"M c #DAD8D2",
"N c #DAD8D3",
"B c #DBD9D4",
"V c #DCDAD5",
"C c #DDDBD5",
"Z c #DDDBD6",
"A c #DEDCD6",
"S c #DEDCD7",
"D c #DEDDD7",
"F c #DFDDD7",
"G c #DFDDD8",
"H c #E0DED9",
"J c #E1DED9",
"K c #E1DFD9",
"L c #E1DFDA",
"P c #E4E2DD",
"I c #E5E3DD",
/* pixels */
"gueqeuqqqqqeueug",
"g24uq4aqqaq442gN",
"u4cLcl;4cllLNgAN",
"d,ABaco#BuclcNLN",
"a4Ldll@2lgNgNgFN",
"edAeagNlelcu=uAN",
"ugclluuaaNggX%Pc",
"d6lNllgqgllu@:LN",
"aqg%3ggeNaalNlCN",
"u6g.OL6dlllfaalN",
"u6c;6c6cgNlcNqlB",
"u,gccuclf*ffl7CN",
"g,uuddNN= :NqqAN",
"u,gu4ldgq%2l2aCN",
"agLJDBBDAIKBNAKN",
"lcczccclcllcNclg"
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 163 2",
"   c #464544",
".  c #5F5E5C",
"X  c #605F5D",
"o  c #636260",
"O  c #646360",
"+  c #666563",
"@  c #6A6967",
"#  c #7B7977",
"$  c #7D7C79",
"%  c #807F7C",
"&  c #83827F",
"*  c #858480",
"=  c #868582",
"-  c #878683",
";  c #888683",
":  c #888784",
">  c #8C8B88",
",  c #8D8C88",
"<  c #8F8E8B",
"1  c #908F8B",
"2  c #918F8C",
"3  c #93928E",
"4  c #949390",
"5  c #959390",
"6  c #959490",
"7  c #979592",
"8  c #989693",
"9  c #989793",
"0  c #9F9E9A",
"q  c #A09E9A",
"w  c #A4A39F",
"e  c #A6A4A0",
"r  c #B1AFAB",
"t  c #B3B2AD",
"y  c #B4B3AE",
"u  c #B6B5B0",
"i  c #B9B7B3",
"p  c #BAB8B4",
"a  c #BAB9B4",
"s  c #BBB9B5",
"d  c #BBBAB5",
"f  c #BBBAB6",
"g  c #BCBAB6",
"h  c #BDBCB7",
"j  c #BEBCB7",
"k  c #BDBCB8",
"l  c #BEBCB8",
"z  c #BEBDB8",
"x  c #BFBDB9",
"c  c #BFBEB9",
"v  c #C0BEB9",
"b  c #C0BEBA",
"n  c #C0BFBA",
"m  c #C1BFBB",
"M  c #C1C0BB",
"N  c #C2C0BC",
"B  c #C2C1BC",
"V  c #C3C1BD",
"C  c #C3C2BD",
"Z  c #C4C2BD",
"A  c #C4C2BE",
"S  c #C4C3BE",
"D  c #C5C3BE",
"F  c #C5C3BF",
"G  c #C5C4BF",
"H  c #C6C4BF",
"J  c #C7C5C0",
"K  c #C7C5C1",
"L  c #C7C6C1",
"P  c #C8C7C2",
"I  c #C9C7C2",
"U  c #C9C7C3",
"Y  c #C9C8C3",
"T  c #CAC8C3",
"R  c #CAC8C4",
"E  c #CAC9C4",
"W  c #CBC9C4",
"Q  c #CBCAC5",
"!  c #CCCAC5",
"~  c #CCCAC6",
"^  c #CCCBC6",
"/  c #CDCBC6",
"(  c #CDCBC7",
")  c #CDCCC7",
"_  c #CECCC7",
"`  c #CECCC8",
"'  c #CECDC8",
"]  c #CFCDC8",
"[  c #CFCDC9",
"{  c #CFCEC9",
"}  c #D0CEC9",
"|  c #D1CFCA",
" . c #D1CFCB",
".. c #D2D0CB",
"X. c #D3D1CC",
"o. c #D3D2CC",
"O. c #D3D2CD",
"+. c #D4D2CD",
"@. c #D5D3CD",
"#. c #D4D3CE",
"$. c #D5D3CE",
"%. c #D5D4CF",
"&. c #D6D4CF",
"*. c #D7D4CF",
"=. c #D7D5CF",
"-. c #D7D5D0",
";. c #D7D6D0",
":. c #D8D5D0",
">. c #D8D6D0",
",. c #D8D6D1",
"<. c #D9D6D1",
"1. c #D9D7D1",
"2. c #D9D7D2",
"3. c #D9D8D2",
"4. c #D9D8D3",
"5. c #DAD8D3",
"6. c #DBD8D3",
"7. c #DAD9D4",
"8. c #DBD9D4",
"9. c #DBDAD4",
"0. c #DBDAD5",
"q. c #DCDAD4",
"w. c #DCDAD5",
"e. c #DCDBD5",
"r. c #DDDBD5",
"t. c #DDDBD6",
"y. c #DEDBD6",
"u. c #DEDCD6",
"i. c #DEDCD7",
"p. c #DFDDD7",
"a. c #DFDDD8",
"s. c #DFDED8",
"d. c #E0DED9",
"f. c #E1DFD9",
"g. c #E1DFDA",
"h. c #E2E0DA",
"j. c #E2E0DB",
"k. c #E3E1DB",
"l. c #E3E1DC",
"z. c #E4E2DD",
"x. c #E5E3DE",
"c. c #E6E4DF",
"v. c #E6E5DF",
"b. c #E7E5DF",
"n. c #E7E5E0",
"m. c #E8E6E0",
"M. c #E8E6E1",
"N. c #E8E7E1",
"B. c #E9E7E1",
"V. c #E9E7E2",
"C. c #E9E8E2",
"Z. c #EAE8E2",
"A. c #EAE8E3",
"S. c #EAE9E3",
"D. c #EBE9E3",
"F. c #EAE9E5",
"G. c #EBE9E4",
"H. c #ECE9E4",
"J. c #ECEAE4",
"K. c #ECEAE5",
"L. c #EDEBE5",
"P. c #EDEBE6",
"I. c #EEECE6",
/* pixels */
"+.+.=.=.=.=.=.=.;.-.-.+.-.+.;.:.-.+.;.;.;.*.+.;.:.+.:.-.+.;.+.+.",
"+.+.R ( ( ( ' R ( ( ( ( ( ( ( ( ( ( ( ( ( ` ( ( ( ( ` ` ( ( +.+.",
"+.=.R x m m x C H x m m x m x x x m H D x x m x x m x m l ] 2.+.",
"+.=.F =.=.;.#.n.y.:.;.;.;.+.;.;.;.;.6.f.g.4.:.;.;.;.;.;.+.A.t.+.",
"#.+.f ..+...0.b.] +.+.+.t.t.6. .+.+. . .;.] m.;.+. .+.+.] m.t.+.",
"#...x +.#...C.5. .-.+.;.0 2 s 4.+.+.+.:.H t.g.t.g.t.+.+.+.m.t.+.",
"#.+.h +...t.m...+.+.+.+.w i X ;.+.+.+.+.( k. .+.;.a.g.t.] k.t.] ",
"#.+.x +...m.0...+.-.+.+.k.; r 6.+.+.;.R t.t.+.+.+. .;.f.f.L.t.+.",
"#.+.x ..t.m.] +.+.+.+.f.% @ s +.+.+.+.R m. .+.+.-.+.+.+.+.L.t.+.",
"*.+.x ..k.+.=.=.+.+.+.+.R U K -.+.;.H t.t. .+.+. . .+.:.] m.t. .",
"#.+.s q.L.( ( ] -.=.+.+.:.;.;.+.:.+.F m. .+.+.-.f.d.+.+.X.m.t.] ",
"#.+.f C.f.q.;.] U ] =.+.+.+.+.+.;.D ;.a. .:.:.] 8 e ] :.] m.t.+.",
"#.X.H L...+.#.t.4.' R ..=.+.+.-.+.F m. .+.+.;.D > $ 3 f.] A.t.+.",
"+.X.H t.+.+.+.+.-.t.+.( ( ..;.;.D ;.f. .+.*.+.;.g.$ 8 f.] m.t.+.",
"+.+.s +.+.+.+.#.....-.4.+.( R ] D m.] -.+.+.;.x = > 3 f.] m.q.] ",
"*.X.D +.+.+.+.+...-.+...=.;.;.C =.t.+.+.+.+.+.+.v s t.+. .m.t.+.",
"+.;.(  .+.:.;.] ;.+.#.#.+.....K m.R R ..;.+.+.+.6.4.+.+. .m.t.+.",
"+.+.s +.+.;.3 = r t.+.#.+.5.m ..f.y.0.' U  .:.+.+.+.+.*. .V.t.+.",
"+.+.v +.;.R O i + y...+.#...x g.....=.a.;.( R -.-.+.+.+.] f.t.] ",
"-.+.l +.+.;.r X O g...+.;.m +.t...=.....4.a.4.' (  .;.;.H t.d.| ",
"+.+.x +.+.;.i < ' ;.+.+.] x k...=.#.=.-.....4.a.;.( ] +.x m.t. .",
"+.+.l +.-.+.+.t.;.+.+.;.m +.t.....-.....#.-.....;.f.t.H U L.t.+.",
"+.+.l +.+.+.+. .+.+.:.] H c.] +.-...y.-...-.-...+.+.;.H  .m.t.] ",
"=.=.s ] :.+.+.+.-.+.;.C f.t.+.+...0.0 8 -.....-.+.;.H ( +.m.t.+.",
"+.-.f D R +.#.#.+.;.] U c.] -.+.t.y   3 ( ;.+.+.-. .D :.] m.t.+.",
"+.+.x +.] U ( +.+.;.C a.4.+.+. .f.8 2 7 ; k. .+.;.H ` ;. .m.t. .",
"+.+.l +.*.#._ U ( ( U m.] -.+.+.:.U ; = m ;.+.+. .D +.+.| m.t.| ",
"-.+.l +.+.+.*.#.( D f.;.:.+.+.+.+.;.;.-.4.+.+.;.D ( ;.+. .b.t.+.",
"+.X.s +.#.+.#.#.-.;. .F ( +.-.:.-.+.+.-.+.+.:.( x +.+.:.+.H.t.] ",
"+.+.t.I.J.J.J.J.A.H.L.A.k.m.L.k.m.L.A.A.H.L.L.c.m.L.L.L.m.m.t.+.",
"+.+.+.;.*.#.+.+.-.+.-.+.;.-.+. .-.-.-.+.-.+.+.;.;.+.;.+.+.+.+.+.",
"*.#.+.+.+.+.+.+.+.+. .+.+.+.+.-. .+.+. .+.+.+.+.+.+.+.+.+.+.+.+."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 254 2",
"   c #2D2D2C",
".  c #373735",
"X  c #393937",
"o  c #3B3B3A",
"O  c #424140",
"+  c #424240",
"@  c #444341",
"#  c #484746",
"$  c #494847",
"%  c #4D4C4B",
"&  c #504F4D",
"*  c #52514F",
"=  c #525150",
"-  c #545351",
";  c #5C5C59",
":  c #5E5D5B",
">  c #5F5E5B",
",  c #5F5E5C",
"<  c #605F5D",
"1  c #63625F",
"2  c #636260",
"3  c #696865",
"4  c #6A6966",
"5  c #6B6A67",
"6  c #6C6B69",
"7  c #6E6D6B",
"8  c #6F6E6B",
"9  c #73726F",
"0  c #737270",
"q  c #747371",
"w  c #757371",
"e  c #7B7A77",
"r  c #7C7B78",
"t  c #81807D",
"y  c #858380",
"u  c #868481",
"i  c #868581",
"p  c #898784",
"a  c #8B8986",
"s  c #8C8B87",
"d  c #8C8B88",
"f  c #8D8C89",
"g  c #8E8D89",
"h  c #908E8B",
"j  c #91908D",
"k  c #959490",
"l  c #969591",
"z  c #979692",
"x  c #999894",
"c  c #9A9895",
"v  c #9C9A96",
"b  c #9E9C98",
"n  c #A09E9A",
"m  c #A2A09C",
"M  c #A2A19D",
"N  c #A3A19E",
"B  c #A4A39F",
"V  c #A9A8A4",
"C  c #ADABA7",
"Z  c #AEACA8",
"A  c #AFADA9",
"S  c #B1AFAB",
"D  c #B2B0AC",
"F  c #B2B1AC",
"G  c #B3B1AD",
"H  c #B3B2AD",
"J  c #B3B2AE",
"K  c #B4B2AE",
"L  c #B5B3AF",
"P  c #B5B4AF",
"I  c #B5B4B0",
"U  c #B6B4B0",
"Y  c #B6B5B0",
"T  c #B6B5B1",
"R  c #B7B5B1",
"E  c #B7B6B2",
"W  c #B8B6B2",
"Q  c #B8B7B2",
"!  c #B8B7B3",
"~  c #B9B7B3",
"^  c #B9B8B3",
"/  c #B9B8B4",
"(  c #BAB9B4",
")  c #BBB9B5",
"_  c #BBBAB5",
"`  c #BCBAB6",
"'  c #BCBBB6",
"]  c #BCBBB7",
"[  c #BDBBB7",
"{  c #BDBCB7",
"}  c #BDBCB8",
"|  c #BEBDB8",
" . c #BFBDB9",
".. c #BFBEB9",
"X. c #C0BFBA",
"o. c #C1BFBA",
"O. c #C1BFBB",
"+. c #C1C0BB",
"@. c #C1C0BC",
"#. c #C2C0BC",
"$. c #C2C1BC",
"%. c #C3C1BC",
"&. c #C3C1BD",
"*. c #C3C2BD",
"=. c #C4C2BD",
"-. c #C4C2BE",
";. c #C4C3BE",
":. c #C5C4BF",
">. c #C6C4BF",
",. c #C6C5C0",
"<. c #C7C5C0",
"1. c #C7C5C1",
"2. c #C7C6C0",
"3. c #C7C6C1",
"4. c #C8C6C1",
"5. c #C8C6C2",
"6. c #C8C7C2",
"7. c #C9C7C2",
"8. c #C9C7C3",
"9. c #C9C8C3",
"0. c #CAC8C3",
"q. c #CAC8C4",
"w. c #CAC9C4",
"e. c #CBC9C4",
"r. c #CBCAC5",
"t. c #CCCAC5",
"y. c #CCCAC6",
"u. c #CDCBC6",
"i. c #CDCBC7",
"p. c #CDCCC7",
"a. c #CECCC7",
"s. c #CECCC8",
"d. c #CECDC8",
"f. c #CFCDC8",
"g. c #CFCDC9",
"h. c #CFCEC9",
"j. c #D0CEC9",
"k. c #D1CFC9",
"l. c #D0CECA",
"z. c #D1CFCA",
"x. c #D1CFCB",
"c. c #D2CFCB",
"v. c #D2D0CB",
"b. c #D2D0CC",
"n. c #D2D1CC",
"m. c #D3D0CC",
"M. c #D3D1CC",
"N. c #D3D1CD",
"B. c #D3D2CD",
"V. c #D4D2CD",
"C. c #D5D3CD",
"Z. c #D4D2CE",
"A. c #D4D3CE",
"S. c #D5D3CE",
"D. c #D6D3CE",
"F. c #D5D4CF",
"G. c #D6D4CE",
"H. c #D6D4CF",
"J. c #D7D4CF",
"K. c #D7D5CF",
"L. c #D6D5D0",
"P. c #D6D5D1",
"I. c #D7D5D0",
"U. c #D7D6D1",
"Y. c #D7D6D3",
"T. c #D8D5D0",
"R. c #D8D6D0",
"E. c #D8D6D1",
"W. c #D8D7D2",
"Q. c #D9D7D2",
"!. c #DAD7D2",
"~. c #D9D8D2",
"^. c #D9D8D3",
"/. c #DAD8D2",
"(. c #DAD8D3",
"). c #DBD9D3",
"_. c #DAD8D4",
"`. c #DAD9D4",
"'. c #DBD9D4",
"]. c #DCDAD4",
"[. c #DCDAD5",
"{. c #DCDBD6",
"}. c #DDDBD6",
"|. c #DEDBD6",
" X c #DEDCD6",
".X c #DEDCD7",
"XX c #DFDDD7",
"oX c #DEDDD8",
"OX c #DFDDD8",
"+X c #E0DED8",
"@X c #E0DED9",
"#X c #E0DFD9",
"$X c #E1DFDA",
"%X c #E2E0DA",
"&X c #E2E0DB",
"*X c #E3E1DC",
"=X c #E3E2DF",
"-X c #E4E2DC",
";X c #E4E2DD",
":X c #E5E3DD",
">X c #E4E3DF",
",X c #E5E3DE",
"<X c #E6E4DF",
"1X c #E7E5DF",
"2X c #E4E3E0",
"3X c #E5E4E0",
"4X c #E6E5E0",
"5X c #E7E5E0",
"6X c #E7E6E2",
"7X c #E8E6E0",
"8X c #E8E6E1",
"9X c #E8E7E1",
"0X c #E9E7E1",
"qX c #E8E6E2",
"wX c #E8E7E2",
"eX c #E9E7E2",
"rX c #E9E8E2",
"tX c #EAE8E3",
"yX c #EBE9E3",
"uX c #EBE9E4",
"iX c #EBEAE5",
"pX c #ECEAE4",
"aX c #ECEAE5",
"sX c #EDEBE5",
"dX c #EDEBE6",
"fX c #EEECE7",
"gX c #EFEDE7",
"hX c #EFEDE8",
"jX c #EEEDEA",
"kX c #EFEDEA",
"lX c #EFEEEA",
"zX c #EFEEEB",
"xX c #F0EEE8",
"cX c #F0EEE9",
"vX c #F1EFE9",
"bX c #F0EEEA",
"nX c #F0EEEB",
"mX c #F0EFEA",
"MX c #F0EFEB",
"NX c #F1F0EB",
"BX c #F2F0EA",
"VX c #F2F0EB",
"CX c #F3F1EB",
"ZX c #F2F0EC",
"AX c #F3F1EC",
"SX c #F3F2EE",
"DX c #F4F2EC",
"FX c #F5F3ED",
"GX c #F5F3EE",
"HX c #F5F4EE",
"JX c #F6F4EF",
"KX c #F8F7F3",
"LX c #FFFCF6",
"PX c gray100",
/* pixels */
"S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.",
"S.S.S.S.S.v.S.S.S.S.M.S.S.M.S.S.C.c.S.S.S.S.S.M.M.S.S.S.S.S.S.c.S.S.M.S.S.M.S.M.M.S.S.M.v.S.S.S.",
"S.S.S.S.H.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.",
"S.S.S.v.y.f.f.f.x.a.c.a.a.a.c.a.c.a.c.a.a.j.j.x.j.j.a.a.c.a.a.x.a.j.x.x.j.j.j.j.j.j.j.a.S.S.S.S.",
"S.S.S.S.:.W I I I I I P ^ ^ I I P P P P ^ P P I I I ^ [ I H I I I W I I I I I I P I H 9.E.S.S.S.",
"S.S.c.(.(.f.E.S.H.S.E.S.dX].S.S.S.S.S.S.S.S.S.S.H.S.H.#X1XXXK.S.H.S.S.K.E.H.H.H.S.K.S.AX].c.S.S.",
"S.S.S.S.H 8.E.S.B.S.c.%X1Xc.S.v.S.S.S.S.S.S.c.S.S.S.v.c.S.XX-XXXv.c.c.S.S.S.v.S.S.S.M.CXE.v.S.S.",
"S.S.S.E.^ 0.S.S.S.S.S.DXH.v.S.S.S.S.c.S.(.S.S.S.S.S.S.S.S.c.(.y.(.eXS.x.S.S.S.S.S.S.M.BX].v.S.S.",
"S.S.v.E.! 0.H.S.A.x.4XeXc.S.v.S.S.S.[.x.*.(.H.S.S.S.S.S.S.S.S.[ CX%X1X*XH.v.S.H.S.S.B.CX(.B.S.S.",
"S.S.S.E.! 0.H.A.S.H.ZXH.S.S.S.S.x.#Xn - t 4 S.S.v.S.S.S.S.H.:.H.6Xa.S.OX4X*XH.v.C.S.c.CX(.c.S.S.",
"S.S.S.H.^ 0.S.S.x.4XeXx.S.S.S.S.c.[.S C LX% l %Xc.S.S.S.S.v...lXS.S.S.v.S.OX4X*XK.B.c.CX(.c.S.S.",
"S.S.S.E.^ 0.E.S.S.CXH.S.S.S.S.S.S.M.E.dXd ; S.S.S.S.S.v.E.*.(.eXf.S.S.S.v.v.H.OX1X%XS.CX(.C.S.S.",
"S.S.S.H.W 0.E.c.4XeXc.S.v.S.S.S.S.S.XXl > -X(.S.S.S.S.S.S...lXS.S.S.S.S.S.S.S.v.S.XX1XDXR.C.S.S.",
"S.S.S.E./ 0.H.S.ZXS.S.S.S.S.S.S.M.).L   i i O.E.S.S.v.E.*.Y.eXc.S.v.S.S.S.B.S.S.S.c.S.DX(.B.S.S.",
"S.S.S.E.W 0.v.4XeXv.S.S.S.S.S.S.S.S.x.x.:.%.x.S.S.S.S.S...lXS.v.S.S.S.S.S.S.S.S.S.S.v.CX(.B.S.S.",
"S.S.v.E./ 9.(.tX:.9.S.H.S.S.v.S.S.S.S.S.E.E.S.S.S.v.(._ (.eXx.S.S.S.S.S.v.v.B.S.S.S.v.CX(.c.S.S.",
"S.S.v.(./ 2.6XSX].f.*.9.S.H.S.S.S.S.M.S.S.v.S.S.S.S.c.P ZXS.B.S.S.S.S.E.#X+XS.S.S.S.x.CX(.C.S.S.",
"S.S.S.H.P 0.KX].S.%XOXa.*.9.S.S.M.S.S.S.S.S.S.S.S.E.] H.6Xc.S.S.S.S.S.y.m N E.E.S.S.c.CX(.c.S.S.",
"S.S.B.(.I OXZXc.S.c.H.%XOXa.*.9.S.S.M.S.S.S.S.S.S.c./ ZXS.S.S.S.S.x.-X* 4 h > (.S.S.S.CX(.B.S.S.",
"S.S.S.(.P iXOXv.S.S.S.c.H.%X%X0.%.j.S.S.S.v.S.v.E./ H.eXc.S.v.S.S.S.S.%.y.p , [.c.S.c.CX(.B.S.S.",
"S.S.v.H./ OXH.S.v.S.S.S.S.c.S.%XE.8.:.f.S.H.S.S.v.P lXS.v.S.S.S.S.S.x.eX-.0 8 ].c.S.c.DX(.B.S.S.",
"S.S.S.(./ 0.H.S.S.S.H.v.S.S.S.c.H.XXH.2.%.x.S.]./ H.eXc.S.S.S.S.S.S.[.w ..2.. v.S.S.B.CX(.c.S.S.",
"S.v.v.H.D 0.H.S.S.S.S.S.S.S.S.S.S.c.E.XXH.2.:.0./ DXS.S.S.S.S.S.A.S.OXg 0 7 D XXS.S.c.CX(.c.S.S.",
"S.S.S.S...c.S.S.v.S.S.v.c.S.S.v.S.S.S.c.(.XX(./ (.1Xv.S.S.B.S.S.A.A.v.OX].XXXXv.S.S.c.DX(.C.S.S.",
"S.S.v.].].f.H.v.S.M.K.%X[.S.S.S.S.S.S.S.S.S.x._ lX2.*.f.H.H.v.S.S.S.S.v.S.v.v.H.C.S.c.CX(.c.S.S.",
"S.S.S.E.D 0.H.H.M.(.0.l Z (.S.S.S.S.S.S.S.E.D S.lX*X].2.*.f.H.H.B.S.S.v.S.S.S.S.S.S.B.CX(.B.S.S.",
"S.S.S.H./ 0.H.H.S.a.% c , D [.v.S.S.S.S.S.y.I dXf.v.OX1X].2.*.f.H.S.S.B.S.S.S.S.S.S.C.DX(.B.S.S.",
"S.S.v.(./ 0.H.v.XXS + PXd 2 eXc.S.S.S.S.E.H S.#Xc.S.v.S.OX4X].2.*.c.H.B.S.B.S.v.C.S.a.eX].B.S.S.",
"A.A.S.E./ 0.H.L.S.H.6 a o 1 1Xx.S.M.S.S.y.H dXS.S.S.S.S.h.v.OX4X].6.2.x.U.S.S.v.C.(.] eX].B.C.S.",
"A.H.v.E./ 0.H.v.S.E.v.c @ N [.M.S.S.S.E.H D.$Xx.S.S.S.S.A.S.h.S.XX1X].9.9.c.S.S.S.a.[ DXR.B.S.S.",
"A.A.A.E.! 0.H.H.v.E.b w W +Xx.S.S.S.K.y.U dXc.S.S.S.S.S.S.A.A.A.c.S.OX1X(.9.8.c.E...r.DX(.B.S.S.",
"I.A.v.Y.! 0.H.L.S.S.(.%X).c.S.S.S.S.E.S A.$Xx.S.S.S.S.S.S.A.S.A.S.B.c.B.XX1X(.0.2.+.S.CX).B.S.S.",
"S.S.S.E.^ 0.H.S.S.S.c.c.v.S.S.S.S.H.0.] lXx.S.S.S.v.S.S.c.c.S.S.v.S.S.S.c.c.XX1XX.c.S.CX(.B.S.S.",
"S.S.S.E./ 0.H.S.S.v.S.S.S.S.S.S.B.U.I 4X#Xc.S.S.S.S.v.E.%XXXS.S.S.S.S.S.S.S.S.9.*.S.c.CX(.c.S.S.",
"S.S.S.I.^ 9.E.S.S.S.S.S.S.S.v.S.H.9...MXx.S.v.S.S.v.(.8.r c H.S.v.S.S.S.S.S.S.[ c.S.c.CX(.B.S.S.",
"S.S.S.E./ / 0.S.S.S.S.S.S.S.S.S.^.I 4XXXc.S.S.S.S.E.2.X d x.H.S.S.S.S.S.S.S.9.*.(.B.B.CX(.c.S.S.",
"S.S.S.I.W 1.8.%.y.S.H.v.v.S.S.H.6.*.CXc.S.S.S.S.c.1Xe + s 8 H.S.S.S.B.S.C.S.[ c.S.S.c.CX(.c.S.S.",
"S.S.S.E.W q.E.x.2.2.f.S.H.S.S.E.I 2XXXv.S.S.S.S.x.1X4 i PX# m #Xc.S.S.S.K.:.%.S.C.C.C.CX(.B.S.S.",
"S.S.c.E.W 0.E.S.H.x.2.2.a.S.(.2...ZXc.S.B.S.S.S.c.XXc = V # *.(.S.S.S.c.S._ c.S.B.S.B.CX(.c.S.S.",
"S.S.S.E.W 0.H.S.S.S.S.x.2.:.x.I 6XXXc.S.S.S.S.S.S.c.OXC s O.[.v.S.S.B.(.9.*.(.S.S.S.B.CX(.C.S.S.",
"S.S.S.(.^ 9.K.B.S.S.S.S.(.c.:.a.gXB.K.S.S.S.S.S.S.B.c.XX-X(.B.S.S.S.S.S.( B.S.S.S.S.B.CX(.B.S.S.",
"S.C.B.S.P 9.S.c.c.c.c.c.c.c.B.).:.X.r.v.c.c.v.v.B.c.c.h.a.c.c.c.c.c.S.] { S.c.B.c.c.c.CX(.c.S.S.",
"S.c.S.B.[ K.#XXXXXXXXX+XXXXXXXXXXXU.p.k.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*.XXXXXXXXXXXXXXDX(.c.S.S.",
"S.S.c.(.XXxXCXgXlXlXgXgXdXCXgXgXgXCXlXgXlXgXCXXXdXCXgXCXxXgXxXgXxXlXgXxXCXgXgXgXxXCX#XyX).B.S.S.",
"S.S.S.S.a.S.B.c.c.c.h.c.c.c.h.c.c.c.c.B.h.c.c.a.B.c.c.c.c.c.a.c.c.c.c.c.c.k.c.c.c.c.a.S.S.B.S.S.",
"S.S.S.B.S.B.S.S.B.S.S.S.S.S.S.S.S.S.B.K.S.S.S.K.B.S.S.S.S.S.S.S.S.S.S.B.S.S.B.S.S.S.S.B.C.S.C.S.",
"S.S.C.S.C.S.S.B.S.S.S.S.S.S.S.S.S.S.S.S.S.B.S.B.S.S.B.S.S.S.S.S.S.S.S.S.S.S.S.S.B.S.C.S.S.B.S.S.",
"S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S."
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
};
const int n_xpm_icons = 3;
