/* XPM */
static const char *const xpm_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 110 2",
"   c #3838C2",
".  c #3C3CCC",
"X  c #6867CA",
"o  c #6B6ACA",
"O  c #7674C1",
"+  c #7574C9",
"@  c #A5A3B9",
"#  c #B9B7B3",
"$  c #BAB9B4",
"%  c #BAB9B7",
"&  c #BFBDBC",
"*  c #8C8BC2",
"=  c #8988D1",
"-  c #A1A0C5",
";  c #A3A1CF",
":  c #A7A5C8",
">  c #AEACC6",
",  c #AAA8C9",
"<  c #ADABD1",
"1  c #B7B5CE",
"2  c #C3C1BD",
"3  c #C5C3B9",
"4  c #C5C4BF",
"5  c #CBC9BB",
"6  c #C8C6C1",
"7  c #C8C6C2",
"8  c #C8C6C3",
"9  c #C8C7C2",
"0  c #C9C7C3",
"q  c #C8C6CA",
"w  c #CAC8C3",
"e  c #CAC8C4",
"r  c #CAC8C5",
"t  c #CBC9C4",
"y  c #CBC9C5",
"u  c #CBC9C6",
"i  c #CCCAC5",
"p  c #CDCBC6",
"a  c #CDCBC7",
"s  c #CDCCC7",
"d  c #CECCC7",
"f  c #CECCC9",
"g  c #CFCDC9",
"h  c #C4C2D0",
"j  c #C9C8D1",
"k  c #D0CEC2",
"l  c #D0CEC4",
"z  c #D1CFC4",
"x  c #D0CEC9",
"c  c #D1CFC9",
"v  c #D0CECB",
"b  c #D1CFCA",
"n  c #D1D0C4",
"m  c #D7D5C0",
"M  c #D7D5C7",
"N  c #D3D1CB",
"B  c #D3D1CC",
"V  c #D4D2CD",
"C  c #D5D3CE",
"Z  c #D6D4CF",
"A  c #D8D6C4",
"S  c #DBD9C6",
"D  c #DDDBCC",
"F  c #DCDACF",
"G  c #D5D3D3",
"H  c #D6D4D0",
"J  c #D6D4D1",
"K  c #D6D5D1",
"L  c #D7D5D0",
"P  c #D9D7D1",
"I  c #D8D6D3",
"U  c #D9D7D2",
"Y  c #D9D7D3",
"T  c #D9D7D4",
"R  c #D9D7D5",
"E  c #DAD8D3",
"W  c #DAD8D4",
"Q  c #DAD8D5",
"!  c #DBD9D4",
"~  c #DBD9D5",
"^  c #DAD8D6",
"/  c #DBD9D6",
"(  c #DCDAD4",
")  c #DCDAD5",
"_  c #DDDBD5",
"`  c #DCDAD6",
"'  c #DCDAD7",
"]  c #DDDBD6",
"[  c #DDDBD7",
"{  c #DEDCD6",
"}  c #DEDCD7",
"|  c #DCDAD8",
" . c #DFDDD8",
".. c #E0DED1",
"X. c #E1DFD1",
"o. c #E0DED5",
"O. c #E1DFD5",
"+. c #E1DFD9",
"@. c #E2E0D3",
"#. c #E3E1D3",
"$. c #E3E1D6",
"%. c #E7E5D1",
"&. c #E6E4D2",
"*. c #E6E4D5",
"=. c #E7E5D5",
"-. c #E6E4D6",
";. c #E6E4D7",
":. c #E7E5D7",
">. c #E9E7D4",
",. c #EAE8D4",
/* pixels */
") ) ) ) W O.%./ ) W ) W  .K W ) ",
") ) ) Y >.; X &./ ) Y ) C g ) ) ",
") ) ) W O.1 * k g Y :.O.0 ) ) ) ",
") ) ) ) ) F A  .x n , - O.) W ) ",
") ) W ) ) Z w  .W S O + %.W W ) ",
") W W ) [ E 0 x 0 v :.D y [ ) ) ",
") ) O.[ E w # Z )  .W / C y ) W ",
") J h c w c y  .W W ) F [ C Z [ ",
"&.<   5 J E w  .) W ) ) E [ ) F ",
"W ) % 0 g 6 % C ) [ [ ) ) E W ) ",
"W  .C & W ) 2 g 0 w C W [ [ ) ) ",
"W ) J m n K w  .) Z y w y C W ) ",
") W #.o : M l ) E [ [ ) Z d E ) ",
"W W O.= > 3 @ W F ) ) W [ [ ) F ",
") ) ) ,.&.q . j O.W ) ) W ) W ) ",
"W W ) W E [ E ) ) ) ) ) ) ) ) ) "
};

/* XPM */
static const char *const xpm_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 212 2",
"   c #0202D7",
".  c #0404D8",
"X  c #0C0CD4",
"o  c #0808DE",
"O  c #0101E9",
"+  c #0000EB",
"@  c #0000F7",
"#  c #0000F9",
"$  c #0000FC",
"%  c #2222C9",
"&  c #3232CE",
"*  c #4948B2",
"=  c #4D4CB6",
"-  c #6665AF",
";  c #7776A3",
":  c #7473B0",
">  c #7B7AB6",
",  c #7D7CBD",
"<  c #4747C6",
"1  c #4746CD",
"2  c #6665C0",
"3  c #6C6BC5",
"4  c #7271C0",
"5  c #8F8E9B",
"6  c #9B9A96",
"7  c #8180B4",
"8  c #9694A6",
"9  c #9D9BAF",
"0  c #A3A29E",
"q  c #A4A29F",
"w  c #A6A598",
"e  c #AFAEAA",
"r  c #A1A0B2",
"t  c #ABA9B9",
"y  c #B2B0A9",
"u  c #B2B0AE",
"i  c #B4B2AE",
"p  c #B4B2AF",
"a  c #B4B3AE",
"s  c #B5B3AF",
"d  c #B5B4AF",
"f  c #B9B8AE",
"g  c #BEBDA8",
"h  c #B5B3B3",
"j  c #B5B4B0",
"k  c #B6B4B0",
"l  c #B6B5B0",
"z  c #B7B5B1",
"x  c #B7B6B1",
"c  c #B7B6B2",
"v  c #B6B4B4",
"b  c #B8B6B2",
"n  c #B8B6B3",
"m  c #B8B7B2",
"M  c #B8B7B3",
"N  c #B9B7B3",
"B  c #B9B8B6",
"V  c #BAB8B4",
"C  c #BBB9B5",
"Z  c #BBBAB5",
"A  c #BBBAB7",
"S  c #BCBAB6",
"D  c #BDBBB7",
"F  c #BEBDB3",
"G  c #BFBDB3",
"H  c #BCBBBD",
"J  c #BCBBBF",
"K  c #BEBCB8",
"L  c #BEBDB8",
"P  c #BFBDB9",
"I  c #BFBDBA",
"U  c #BFBEB9",
"Y  c #8988C4",
"T  c #9190C2",
"R  c #9997C3",
"E  c #9D9BC4",
"W  c #C0BEB2",
"Q  c #C0BEB9",
"!  c #C0BEBA",
"~  c #C7C5B4",
"^  c #C2C0BB",
"/  c #C2C0BC",
"(  c #C3C1BC",
")  c #C3C1BD",
"_  c #C3C2BD",
"`  c #C4C2BE",
"'  c #C4C2BF",
"]  c #C5C3BE",
"[  c #C5C3BF",
"{  c #C6C4B9",
"}  c #C8C6B5",
"|  c #C9C7B7",
" . c #C8C7BB",
".. c #CAC9BF",
"X. c #CFCDB8",
"o. c #C6C4C0",
"O. c #C6C5C0",
"+. c #C7C5C1",
"@. c #C5C4C8",
"#. c #C9C7C3",
"$. c #C9C7C4",
"%. c #CAC8C3",
"&. c #CAC8C4",
"*. c #CAC9C4",
"=. c #CDCBC2",
"-. c #CCCAC5",
";. c #CCCAC6",
":. c #CCCBC6",
">. c #CDCBC6",
",. c #CDCBC7",
"<. c #CECCC2",
"1. c #CECCC7",
"2. c #CECCC8",
"3. c #CFCDC8",
"4. c #CFCECA",
"5. c #D1CFC7",
"6. c #D0CEC9",
"7. c #D0CECA",
"8. c #D1CFCA",
"9. c #D6D4C2",
"0. c #D1D0CB",
"q. c #D2D0C9",
"w. c #D2D0CB",
"e. c #D3D1CC",
"r. c #D3D2CD",
"t. c #D5D3CC",
"y. c #D5D3CE",
"u. c #D6D4CF",
"i. c #DFDDCA",
"p. c #DFDDCF",
"a. c #D4D2D0",
"s. c #D6D4D0",
"d. c #D6D4D1",
"f. c #D7D5D0",
"g. c #D7D5D1",
"h. c #D8D6D1",
"j. c #D9D7D2",
"k. c #D9D7D3",
"l. c #D8D6D4",
"z. c #D8D6D5",
"x. c #D9D7D4",
"c. c #D9D7D6",
"v. c #DAD8D3",
"b. c #DBD9D3",
"n. c #D9D8D5",
"m. c #DAD8D4",
"M. c #DAD8D5",
"N. c #DBD9D4",
"B. c #DBD9D5",
"V. c #DAD8D6",
"C. c #DBD9D7",
"Z. c #DCDAD4",
"A. c #DCDAD5",
"S. c #DDDAD5",
"D. c #DDDBD4",
"F. c #DDDBD5",
"G. c #DCDAD6",
"H. c #DDDAD7",
"J. c #DDDBD6",
"K. c #DEDBD6",
"L. c #DEDCD1",
"P. c #DFDDD0",
"I. c #DFDDD3",
"U. c #DEDCD6",
"Y. c #DEDCD7",
"T. c #DFDCD7",
"R. c #DFDDD6",
"E. c #DCDAD8",
"W. c #DDDBD8",
"Q. c #DDDBD9",
"!. c #DEDCD8",
"~. c #DFDDD8",
"^. c #DFDDD9",
"/. c #E0DECC",
"(. c #E0DED7",
"). c #E1DFD7",
"_. c #E0DDD8",
"`. c #E0DDD9",
"'. c #E0DED8",
"]. c #E0DED9",
"[. c #E1DED9",
"{. c #E1DFD9",
"}. c #E0DEDA",
"|. c #E1DFDA",
" X c #E1DFDD",
".X c #E5E3CE",
"XX c #E6E4CE",
"oX c #E2E0D0",
"OX c #E3E1D4",
"+X c #E4E2D4",
"@X c #E5E3D4",
"#X c #E6E4D5",
"$X c #E7E4D5",
"%X c #E7E5D6",
"&X c #E3E0D8",
"*X c #E3E1D9",
"=X c #E2E0DA",
"-X c #E3E1DC",
";X c #E4E2DD",
":X c #E5E3DE",
">X c #E6E4D9",
",X c #E7E5D9",
"<X c #E6E4DF",
"1X c #E7E4DF",
"2X c #E9E6D3",
"3X c #E9E7DD",
"4X c #EAE8D3",
"5X c #EAE8D5",
"6X c #ECE9D8",
"7X c #EEECDA",
"8X c #F3F1DB",
"9X c #E9E7E2",
/* pixels */
"A.A.A.A.A.A.A.A.A.N.A.N.N.N.A.N.A.A.A.A.Z.G.Z.G.Z.v.K.K.v.K.G.G.",
"A.A.A.A.A.A.A.A.A.A.N.K.).N.N.A.A.A.A.A.G.Z.G.Z.v.G.v.y.K.v.G.Z.",
"A.A.A.A.A.A.A.A.A.N.|.@.; b.A.N.A.N.A.A.G.G.N.G.Z.|.D 4.K.v.Z.G.",
"A.A.A.A.A.A.A.A.A.x.XX< $ > 7XA.v.N.A.N.G.N.G.N.|._ _ |.G.Z.G.Z.",
"A.A.A.A.A.A.A.A.N.N.OXY % 9 G 4.|.T.N.N.N.G.N.T.1.Z ).v.G.v.G.Z.",
"A.A.A.A.A.A.A.A.A.A.C./.g 3X7.V b 4.T.T.v.z.E.y.x K.G.Z.Z.G.Z.G.",
"A.A.A.A.A.A.A.A.A.N.A.d.j C.K.|.0.V N 4.T.5XXXV y.T.v.G.G.Z.G.Z.",
"A.A.A.A.A.A.A.A.A.N.A.A.l N.N.v.K.|.y.V W 3 = =.).N.G.Z.Z.G.Z.G.",
"A.A.A.A.A.A.A.A.A.A.N.A.j k.A.A.N.v.T.9Xy . + J |.N.N.G.G.G.Z.G.",
"A.A.A.A.A.A.A.A.A.A.A.A.l v.N.N.T.T.:.l  .R 7 { T.N.G.G.G.G.G.Z.",
"A.A.A.A.A.A.A.A.A.N.A.A.l v.|.A.$.l D d.|.%X5X[ [ ).N.G.v.G.Z.G.",
"A.A.A.A.A.A.A.N.A.A.v.A.V N.+.l U d.|.N.v.N.v.|._ +.T.N.G.v.G.Z.",
"A.A.A.A.A.N.A.A.v.A.|.A.q i ! A.|.K.v.N.G.v.Z.v.|.D *.|.v.G.v.G.",
"A.N.A.N.x.N.b.A.|.v.[ N 0 t.-XA.N.N.G.N.Z.G.G.v.N.).D :.R.Z.Z.G.",
"A.A.N.N.>XA.|.v.! l ! |.D e.A.N.G.v.G.G.G.Z.G.G.N.N.R.Z 0.K.Z.G.",
"A.N.A.I.t t.[ i +.K.|.|.b e.T.N.Z.G.Z.G.Z.G.G.N.G.N.G.Z.u.G.v.Z.",
"N.z.5X, $ * X.-X;XA.d.|.x e.K.N.G.K.G.Z.G.G.G.Z.v.G.Z.G.I.N.G.G.",
"N.z.%XE   - ~ V 1.v.(.:XV e.K.N.Z.v.Z.G.G.G.Z.G.K.v.G.v.v.N.v.G.",
"A.A.N.>X~ w d.4.V d V 4.x v.|.N.v.Z.v.G.N.G.N.N.G.Z.G.Z.Z.G.G.G.",
"A.N.N.N.T.u l T.|.K.4.! 6 e :.v.|.R.G.v.N.N.E.N.Z.G.Z.G.G.Z.G.Z.",
"A.N.A.N.T.U U ^ |.v.K.:X! ^ ! l Z *.v.T.).K.N.N.v.G.v.G.Z.K.Z.G.",
"A.A.N.N.T.+.+._ *.K.v.|.D 1.9XN.0.D d N +.d.).).K.v.Z.G.G.v.G.Z.",
"A.A.N.N.G.j.d K.l d.N.|.D :.K.N.K.|.K.r.^ x x #.u.).R.K.v.G.Z.G.",
"A.A.A.A.N.T.N I.d.N K.|.D :.|.N.N.v.G.K.|.K.r.! x x #.y.G.Z.v.Z.",
"A.A.A.N.N.T.1.8 |.+.! <XU :.K.N.Z.Z.G.v.v.v.K.).T.r.! x r.G.G.G.",
"A.A.A.A.x.5X: @ 2 8Xv d.+._ |.N.N.G.Z.G.G.G.G.v.G.K.).K.G.G.G.Z.",
"A.A.A.A.N.%XT O : | a.D 1...|.v.N.G.G.Z.G.Z.Z.Z.G.v.v.Z.G.v.Z.G.",
"A.A.A.A.N.N.%X9.+X$.M F 5 r >Xv.G.G.Z.G.Z.G.G.Z.G.G.G.Z.G.Z.G.Z.",
"A.A.A.A.N.A.N.C.j.R.).f X O J *Xj.G.Z.G.Z.G.Z.G.Z.G.Z.G.Z.G.Z.G.",
"A.A.A.A.N.A.N.N.G.v.G.I.1 & 0.K.Z.G.G.Z.G.Z.G.Z.G.Z.G.Z.G.Z.G.Z.",
"A.A.A.A.A.A.A.A.v.G.G.K././.R.N.Z.G.Z.G.Z.G.Z.G.Z.G.Z.G.Z.G.Z.G.",
"A.A.A.A.A.A.A.A.Z.Z.G.v.N.G.v.G.v.Z.G.Z.G.Z.G.Z.G.Z.G.Z.G.Z.G.Z."
};

/* XPM */
static const char *const xpm_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 94 2",
"   c #2322AA",
".  c #2B2BA0",
"X  c #2727BC",
"o  c #2D2DB4",
"O  c #3C3CB5",
"+  c #0202CC",
"@  c #0E0DC5",
"#  c #0202D2",
"$  c #1010C4",
"%  c #1414CE",
"&  c #1A1ACA",
"*  c #0000E2",
"=  c #0000EB",
"-  c #0000F4",
";  c #0000FD",
":  c #2222C1",
">  c #4E4E9E",
",  c #4545AB",
"<  c #4F4FA1",
"1  c #4140B9",
"2  c #5150AA",
"3  c #5B5AAB",
"4  c #6E6D93",
"5  c #737290",
"6  c #7B7A90",
"7  c #6362A4",
"8  c #6867A7",
"9  c #7B7AB6",
"0  c #83827F",
"q  c #878683",
"w  c #908F98",
"e  c #9A9988",
"r  c #959392",
"t  c #9E9D98",
"y  c #8E8CAE",
"u  c #8D8CB5",
"i  c #918FAE",
"p  c #9F9DB2",
"a  c #A19F9C",
"s  c #A09EA5",
"d  c #A09FB9",
"f  c #A5A4A0",
"g  c #A7A6AE",
"h  c #A8A6A2",
"j  c #ABA9A5",
"k  c #AEACA8",
"l  c #A9A7BC",
"z  c #ACAAB3",
"x  c #B0AFA0",
"c  c #B0AEAA",
"v  c #B0AFB7",
"b  c #B1AFBD",
"n  c #B2B1AD",
"m  c #B8B7A6",
"M  c #B8B6AD",
"N  c #BAB8AD",
"B  c #B6B4B0",
"V  c #B3B2BC",
"C  c #B8B7B2",
"Z  c #BBB9B4",
"A  c #BEBDB9",
"S  c #C0BEB0",
"D  c #C0BEBA",
"F  c #C3C1BD",
"G  c #CFCDBD",
"H  c #C6C4C1",
"J  c #C8C6C1",
"K  c #CBC9C4",
"L  c #CECCC8",
"P  c #D0CECA",
"I  c #D5D3C2",
"U  c #D3D1CC",
"Y  c #D8D6C2",
"T  c #DAD8C1",
"R  c #D6D4D0",
"E  c #D8D6D2",
"W  c #DBD9D4",
"Q  c #DEDCD8",
"!  c #E0DEC5",
"~  c #E1DFC8",
"^  c #E1DFD2",
"/  c #E0DED9",
"(  c #E2E0CA",
")  c #E4E2D5",
"_  c #E3E1DB",
"`  c #E8E6D1",
"'  c #E9E7DA",
"]  c #ECEAD5",
"[  c #EBE9DE",
"{  c #F2F0DC",
"}  c #E5E3E1",
"|  c #E8E6E1",
" . c #ECEAE2",
".. c #F0EEE2",
/* pixels */
"W W W W W W W W W W W W W W W W Q W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W Q ",
"W W W W W W W W W W W Q W W W W W W W W W W W W W W W W W W W Q W W W W W W W W W W W W W W W W ",
"W W W W W W Q W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W ",
"W W W W W W W W W W W W W W W W W W W E W W W W W W W W W W W W W W W W W W W W P W W W W W W W ",
"Q W W W W W W W W W W W W W W W E [ x m [ E W W W W W W W Q W W W W W W Q E / c K Q W W W W W W ",
"W W W W W W W W W W W W W W W W ) b @ : H W E W W W W W W W W W W W W W E / A C / W W W W W W W ",
"W W W W W W W W W W W W W W W W ` , ; ; 7 { Q W W W W W W W W W W W W W / K j ) W W W W W W W W ",
"W W W W W W Q W W W W W W W W W ) p # % w c L / Q W W W W W W W W W W Q E f W W W W W W W W W W ",
"W W W W W Q W W W W W W W W W W W [ t k ..J h k L / / W W W W W E E W / h U Q W W Q W W W W Q W ",
"W W Q W W W W W W W W W W W W W W / Z H / Q / K h k F / / W W W E E _ k F / W Q W W W W W W W W ",
"W W W W W W W W W W Q W W W W W R / n A / W W Q / K k h H Q W W ' | Z Z _ E Q E W W W W W W W W ",
"W W W W W W W W W W W W W W W W W / F n / W W W W / _ U c h J ( i s N _ W Q E Q W W W W W W W W ",
"W W W W W Q Q W W W W W W W Q W W Q J c / W W W W W W Q / P m < - + v ) W W W W W W W W W W W W ",
"W W W W W W W W W W W W W W W W W / J k / W W W W W W W Q } T   ; = i ' R W W W W W W W W W W W ",
"Q W W W W W W W W W W Q W W W W W Q J k / W W W E W W _ P k k z X 2 S _ W W W W W W W W W W W W ",
"W W W W W W W W W W W W W W W W W / J k / W W W W / U k h J / _ ~ ` c D / W W W W W W W W W Q W ",
"Q W W W W W W W W W W W W W W W W ) H k / E Q Q L k h J / Q W R Q W Q n F ) E Q W W W W W W W W ",
"W W W W W W Q W W W W W W W W W W Q H k [ Q K j h J / Q W W W W R W W Q n F _ E W W W W W W W W ",
"W W W W W W W W W W W W W W W W W Q K n P h k P _ Q W W W W W W W W W W / k K / W W W W Q W W W ",
"W W W W W W W W W W W W W W W W / / Z 0 n P / Q W W W W W W W W W W W W Q E j U Q W W W W W W W ",
"W W W W W W W W W W W W W W Q W J h j a ' Q R W W W W W W W W W W W W W W Q W j P / W W W W W W ",
"W W W W W W W R W W R W / Q D h k U Q f Q E W W W W Q W W W W W W W W W W W W R j P W W W W W W ",
"W W W W W W W ' Q R _ W D f C U / Q U f Q W W W W W W W W W W W W W W W W W W Q P M Q W W W W W ",
"W W W W E Q ) g F ' A h n W / W W W W f Q W W W W W W W W W W W W W W W W R W W Q Q W W W W E Q ",
"W W W W W ' 9 * & r A R Q Q W W W W R f W W W W W W W W W W Q W W W W W W W W W W W W W W W W W ",
"Q W W W W T o ; = 4 ) Q Q Q W W W W W f Q W W W W W W W W W W W W W W W W W W W W W W W W W W Q ",
"W W W W W _ l $ . Z j h B P W _ W W U h Q W W W W W W W W W W W W W W W ^ W W W W W W W W W W W ",
"W W W W W W / T e n } U D h f c J W Q j W W W W W W W W W W W W W W W W Q W W W W W W W W W W W ",
"W W W W W W U ' C f Z _ Q / R H c f j r Q _ Q W R W W W W W W W W W W W W W W W W W W W W W W W ",
"Q W W W W W W Q F M n K Q W W Q _ W J q t n J W _ Q W W W W W W W W W W W W W W W W W W W W W W ",
"W W W W W W Q W W h U h W W W W W W ' c P J c f c J W _ / W W W W W W W W W W W Q W W W W W W W ",
"W W W W W W W E _ j U J n _ R W W W Q f U _ / W F c f k F R / ) W W W W W W W W W W W W W W W Q ",
"W W W W W Q W W / F n [ n F / W W W / h U W W W / _ W F n f j D E _ ) W E W W W W W W W W W W W ",
"W W W W W W W W W U f Q W f U W W E / f U Q W W W E W / _ W L n f j D E _ ) W E E W W W W W W W ",
"W W W W W W W W W ' h K Q L j / W W / h P W W W W W W W W W / ) W K n h j D E _ _ Q E W W W W W ",
"Q W W W W W W W W / A Z  .Q Z A / W / h P Q W W W W W W E W W W W Q } W K n h j A U Q W W W W W ",
"W W W W W W W W W W ) 6 d ) / h L Q Q h U Q W W W W W Q W W W W W W W W / Q Q K n D Q W W W W W ",
"W W W W W Q W W E ` u = * u [ U h W / j L Q W W W W W W W W W Q W W W W W W E / ) Q W W Q W W W ",
"W W W W W W W W E ` 3 ; ; < ` ' D k  .n A / E W W W W W W W W W W W W W W W W W E W W W Q W W W ",
"W W W W W W W W W Q P O 1 B f A | n L D H Q W W W W W W W W W W W W W W W W W W W W W W W W W W ",
"W W W W W W W W W W Q ( ( } E B f H N r k [ W W W W W W W W W Q W W W W Q W W W W W W W Q W W W ",
"W W W W W W W W W W W E Q U W / P M 5 + % V Q E W W W W W W W W W W W W W W W W Q W W W W W W W ",
"W W W Q W W W W W W W W W W W W Q ] , ; - 8 ] E W W Q W W W W W W Q W W W W W W W W W W W Q W W ",
"W W W W W W W Q W W W W W W W W E / b @ : J / W Q W W W W W W W W W W W W W W W W W W W W W W W ",
"W W W W W W W W W W W W W W W W W W ) G I ) W W W W W W W W W W W W W W W W W W W W W W W W W W ",
"W W Q W W W W W W W W W W W W W W W E Q W W W W W W W W W Q W W W W W W W W W W W Q W W W W W W ",
"W W W W W W W W W W W Q W W W W W W W W W W W W W W W W W W W W W W W W Q W W W W W W W W W W W ",
"W W W W W W W Q W W W W W W W W W W W W W W W W W Q W W W W W W W W W W W W W W W W W W W W Q W "
};

const char *const *const xpm_icons[] = {
    xpm_icon_0,
    xpm_icon_1,
    xpm_icon_2,
};
const int n_xpm_icons = 3;
